name: VPS Bug Report
description: File a bug report for a VPS service.
title: "[Bug]: "
labels: ["bug", "vps"]
#type: issue
body:
  - type: markdown
    attributes:
      value: |
        If you found a bug or an issue in a VPS service, please fill out this template as best as you can. If you're unsure about something, just leave it blank and we'll try to help.
  - type: input
    id: service_name
    attributes:
      label: Service Name
      description: What is the name of the service experiencing the issue?
      placeholder: ex. My VPS
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe what happened in as much detail as possible.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
      default: 0
  - type: dropdown
    id: service_part
    attributes:
      label: What part of the service is experiencing the issue?
      required: true
      description: Which part of the service is experiencing the issue? (Select all that apply)
      multiple: true
      options:
        - Console
        - SSH
  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: If applicable, please provide any relevant logs or error messages.
      placeholder: Paste any relevant logs or error messages here.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Service
      description: By submitting this issue, you agree to follow our [Terms of Service](https://dash.stingerhost.eu/index.php?/page/vop/).
      options:
        - label: I agree to follow the Stingerhost Terms of Service
          required: true
