name: Add a New Game Server
description: Request the addition of a new game server service.
title: "[Request]: "
labels: ["enhancement", "game servers"]
type: feature_request
body:
  - type: markdown
    attributes:
      value: |
        If you would like to request the addition of a new game server service, please fill out this template as best as you can. If you're unsure about something, just leave it blank and we'll try to help.
  - type: input
    id: game
    attributes:
      label: Game Name
      description: What is the name of the game you would like to see supported?
      placeholder: ex. Valheim
    validations:
      required: true
  - type: input
    id: server_software
    attributes:
      label: Server Software
      description: What is the name of the server software for this game?
      placeholder: ex. valheim-server
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website
      description: What is the official website for this game or its server software?
      placeholder: ex. https://www.valheimgame.com/
  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Why do you want this game server to be supported? Please provide as much detail as possible.
      placeholder: ex. "I want to host a Valheim server for my friends and I to play on."
    validations:
      required: true
      default: 0
  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Service
      description: By submitting this issue, you agree to follow our [Terms of Service](https://dash.stingerhost.eu/index.php?/page/vop/).
      options:
        - label: I agree to follow the Stingerhost Terms of Service
      required: true
